# Generated by Django 4.2.25 on 2025-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('blogger', 'Blogger'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
